FROM golang:1.25.5-trixie

RUN set -ex \
  && apt update \
  && apt install -y \
    git \
    curl \
    bash \
    unzip \
  && go install "github.com/air-verse/air@v1.63.6" \
  && go install "github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0" \
  && curl -fsSL https://bun.com/install | bash -s "bun-v1.3.5"

ENV PATH="/root/.bun/bin:${PATH}"

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
