// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	KeyHash    string
	KeyPrefix  string
	Name       string
	CreatedAt  sql.NullTime
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
}

type Token struct {
	ID            uuid.UUID
	TokenJti      string
	UserID        uuid.UUID
	IssuedAt      sql.NullTime
	ExpiresAt     time.Time
	RevokedAt     sql.NullTime
	RevokedReason sql.NullString
}

type TranscriptionLog struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ApiKeyID        uuid.UUID
	StartedAt       time.Time
	EndedAt         sql.NullTime
	DurationSeconds sql.NullString
	Status          string
	ErrorMessage    sql.NullString
	DeepgramParams  json.RawMessage
	BytesSent       int64
	ClientIp        sql.NullString
}

type TrialApiKey struct {
	ID                uuid.UUID
	KeyHash           string
	KeyPrefix         string
	DeviceFingerprint string
	CreatedAt         sql.NullTime
	ExpiresAt         time.Time
	LastUsedAt        sql.NullTime
	RevokedAt         sql.NullTime
}

type TrialLimit struct {
	ID                        int32
	MaxDurationSeconds        int32
	MaxSessions               int32
	MaxSessionDurationSeconds int32
	ExpiryDays                int32
	UpdatedAt                 sql.NullTime
}

type TrialUsage struct {
	ID              uuid.UUID
	TrialKeyID      uuid.UUID
	StartedAt       time.Time
	EndedAt         sql.NullTime
	DurationSeconds sql.NullString
	Status          string
	ErrorMessage    sql.NullString
	DeepgramParams  json.RawMessage
	BytesSent       int64
	ClientIp        sql.NullString
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	UserType     string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
