// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	UserType     string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
