// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trial.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cleanupExpiredTrialKeys = `-- name: CleanupExpiredTrialKeys :exec
UPDATE trial_api_keys SET revoked_at = NOW() WHERE expires_at <= NOW() AND revoked_at IS NULL
`

func (q *Queries) CleanupExpiredTrialKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredTrialKeys)
	return err
}

const countActiveTrialAPIKeys = `-- name: CountActiveTrialAPIKeys :one
SELECT COUNT(*) FROM trial_api_keys WHERE revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountActiveTrialAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTrialAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllTrialUsageLogs = `-- name: CountAllTrialUsageLogs :one
SELECT COUNT(*) FROM trial_usage
`

func (q *Queries) CountAllTrialUsageLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllTrialUsageLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrialAPIKeys = `-- name: CountTrialAPIKeys :one
SELECT COUNT(*) FROM trial_api_keys
`

func (q *Queries) CountTrialAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrialAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrialSessions = `-- name: CountTrialSessions :one
SELECT COUNT(*) FROM trial_usage WHERE trial_key_id = $1
`

func (q *Queries) CountTrialSessions(ctx context.Context, trialKeyID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrialSessions, trialKeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrialUsageLogs = `-- name: CountTrialUsageLogs :one
SELECT COUNT(*) FROM trial_usage WHERE trial_key_id = $1
`

func (q *Queries) CountTrialUsageLogs(ctx context.Context, trialKeyID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrialUsageLogs, trialKeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrialAPIKey = `-- name: CreateTrialAPIKey :one

INSERT INTO trial_api_keys (key_hash, key_prefix, device_fingerprint, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, key_hash, key_prefix, device_fingerprint, created_at, expires_at, last_used_at, revoked_at
`

type CreateTrialAPIKeyParams struct {
	KeyHash           string
	KeyPrefix         string
	DeviceFingerprint string
	ExpiresAt         time.Time
}

// =====================
// TRIAL API KEY QUERIES
// =====================
func (q *Queries) CreateTrialAPIKey(ctx context.Context, arg CreateTrialAPIKeyParams) (TrialApiKey, error) {
	row := q.db.QueryRowContext(ctx, createTrialAPIKey,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.DeviceFingerprint,
		arg.ExpiresAt,
	)
	var i TrialApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.DeviceFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createTrialUsageLog = `-- name: CreateTrialUsageLog :one

INSERT INTO trial_usage (trial_key_id, deepgram_params, client_ip)
VALUES ($1, $2, $3)
RETURNING id, trial_key_id, started_at, ended_at, duration_seconds, status, error_message, deepgram_params, bytes_sent, client_ip
`

type CreateTrialUsageLogParams struct {
	TrialKeyID     uuid.UUID
	DeepgramParams json.RawMessage
	ClientIp       sql.NullString
}

// =====================
// TRIAL USAGE QUERIES
// =====================
func (q *Queries) CreateTrialUsageLog(ctx context.Context, arg CreateTrialUsageLogParams) (TrialUsage, error) {
	row := q.db.QueryRowContext(ctx, createTrialUsageLog, arg.TrialKeyID, arg.DeepgramParams, arg.ClientIp)
	var i TrialUsage
	err := row.Scan(
		&i.ID,
		&i.TrialKeyID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Status,
		&i.ErrorMessage,
		&i.DeepgramParams,
		&i.BytesSent,
		&i.ClientIp,
	)
	return i, err
}

const getAllTrialUsageSummary = `-- name: GetAllTrialUsageSummary :one
SELECT
    COUNT(DISTINCT tak.id) as total_trial_keys,
    COUNT(DISTINCT CASE WHEN tak.revoked_at IS NULL AND tak.expires_at > NOW() THEN tak.id END) as active_trial_keys,
    COALESCE(SUM(tu.duration_seconds), 0)::DECIMAL(12,3) as total_duration_seconds,
    COUNT(tu.id) as total_sessions,
    COALESCE(SUM(tu.bytes_sent), 0) as total_bytes_sent
FROM trial_api_keys tak
LEFT JOIN trial_usage tu ON tak.id = tu.trial_key_id
WHERE tu.started_at >= $1 AND tu.started_at < $2
`

type GetAllTrialUsageSummaryParams struct {
	StartDate time.Time
	EndDate   time.Time
}

type GetAllTrialUsageSummaryRow struct {
	TotalTrialKeys       int64
	ActiveTrialKeys      int64
	TotalDurationSeconds string
	TotalSessions        int64
	TotalBytesSent       interface{}
}

func (q *Queries) GetAllTrialUsageSummary(ctx context.Context, arg GetAllTrialUsageSummaryParams) (GetAllTrialUsageSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getAllTrialUsageSummary, arg.StartDate, arg.EndDate)
	var i GetAllTrialUsageSummaryRow
	err := row.Scan(
		&i.TotalTrialKeys,
		&i.ActiveTrialKeys,
		&i.TotalDurationSeconds,
		&i.TotalSessions,
		&i.TotalBytesSent,
	)
	return i, err
}

const getTrialAPIKeyByFingerprint = `-- name: GetTrialAPIKeyByFingerprint :one
SELECT id, key_hash, key_prefix, device_fingerprint, created_at, expires_at, last_used_at, revoked_at FROM trial_api_keys WHERE device_fingerprint = $1
`

func (q *Queries) GetTrialAPIKeyByFingerprint(ctx context.Context, deviceFingerprint string) (TrialApiKey, error) {
	row := q.db.QueryRowContext(ctx, getTrialAPIKeyByFingerprint, deviceFingerprint)
	var i TrialApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.DeviceFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTrialAPIKeyByHash = `-- name: GetTrialAPIKeyByHash :one
SELECT id, key_hash, key_prefix, device_fingerprint, created_at, expires_at, last_used_at, revoked_at FROM trial_api_keys WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetTrialAPIKeyByHash(ctx context.Context, keyHash string) (TrialApiKey, error) {
	row := q.db.QueryRowContext(ctx, getTrialAPIKeyByHash, keyHash)
	var i TrialApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.DeviceFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTrialAPIKeyByID = `-- name: GetTrialAPIKeyByID :one
SELECT id, key_hash, key_prefix, device_fingerprint, created_at, expires_at, last_used_at, revoked_at FROM trial_api_keys WHERE id = $1
`

func (q *Queries) GetTrialAPIKeyByID(ctx context.Context, id uuid.UUID) (TrialApiKey, error) {
	row := q.db.QueryRowContext(ctx, getTrialAPIKeyByID, id)
	var i TrialApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.DeviceFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTrialLimits = `-- name: GetTrialLimits :one

SELECT id, max_duration_seconds, max_sessions, max_session_duration_seconds, expiry_days, updated_at FROM trial_limits WHERE id = 1
`

// =====================
// TRIAL LIMITS QUERIES
// =====================
func (q *Queries) GetTrialLimits(ctx context.Context) (TrialLimit, error) {
	row := q.db.QueryRowContext(ctx, getTrialLimits)
	var i TrialLimit
	err := row.Scan(
		&i.ID,
		&i.MaxDurationSeconds,
		&i.MaxSessions,
		&i.MaxSessionDurationSeconds,
		&i.ExpiryDays,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrialUsageLog = `-- name: GetTrialUsageLog :one
SELECT id, trial_key_id, started_at, ended_at, duration_seconds, status, error_message, deepgram_params, bytes_sent, client_ip FROM trial_usage WHERE id = $1
`

func (q *Queries) GetTrialUsageLog(ctx context.Context, id uuid.UUID) (TrialUsage, error) {
	row := q.db.QueryRowContext(ctx, getTrialUsageLog, id)
	var i TrialUsage
	err := row.Scan(
		&i.ID,
		&i.TrialKeyID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Status,
		&i.ErrorMessage,
		&i.DeepgramParams,
		&i.BytesSent,
		&i.ClientIp,
	)
	return i, err
}

const getTrialUsageSummary = `-- name: GetTrialUsageSummary :one
SELECT
    COUNT(*) as total_sessions,
    COALESCE(SUM(duration_seconds), 0)::DECIMAL(12,3) as total_duration_seconds,
    COALESCE(SUM(bytes_sent), 0) as total_bytes_sent
FROM trial_usage
WHERE trial_key_id = $1
`

type GetTrialUsageSummaryRow struct {
	TotalSessions        int64
	TotalDurationSeconds string
	TotalBytesSent       interface{}
}

func (q *Queries) GetTrialUsageSummary(ctx context.Context, trialKeyID uuid.UUID) (GetTrialUsageSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getTrialUsageSummary, trialKeyID)
	var i GetTrialUsageSummaryRow
	err := row.Scan(&i.TotalSessions, &i.TotalDurationSeconds, &i.TotalBytesSent)
	return i, err
}

const getTrialUsageSummaryActive = `-- name: GetTrialUsageSummaryActive :one
SELECT
    COUNT(*) as total_sessions,
    COALESCE(SUM(duration_seconds), 0)::DECIMAL(12,3) as total_duration_seconds,
    COALESCE(SUM(bytes_sent), 0) as total_bytes_sent
FROM trial_usage
WHERE trial_key_id = $1 AND (status = 'completed' OR status = 'timeout')
`

type GetTrialUsageSummaryActiveRow struct {
	TotalSessions        int64
	TotalDurationSeconds string
	TotalBytesSent       interface{}
}

func (q *Queries) GetTrialUsageSummaryActive(ctx context.Context, trialKeyID uuid.UUID) (GetTrialUsageSummaryActiveRow, error) {
	row := q.db.QueryRowContext(ctx, getTrialUsageSummaryActive, trialKeyID)
	var i GetTrialUsageSummaryActiveRow
	err := row.Scan(&i.TotalSessions, &i.TotalDurationSeconds, &i.TotalBytesSent)
	return i, err
}

const listAllTrialAPIKeys = `-- name: ListAllTrialAPIKeys :many

SELECT
    tak.id, tak.key_hash, tak.key_prefix, tak.device_fingerprint, tak.created_at, tak.expires_at, tak.last_used_at, tak.revoked_at,
    COALESCE(usage_stats.total_sessions, 0)::bigint as total_sessions,
    COALESCE(usage_stats.total_duration_seconds, 0)::DECIMAL(12,3) as total_duration_seconds
FROM trial_api_keys tak
LEFT JOIN (
    SELECT
        trial_key_id,
        COUNT(*) as total_sessions,
        SUM(duration_seconds) as total_duration_seconds
    FROM trial_usage
    GROUP BY trial_key_id
) usage_stats ON tak.id = usage_stats.trial_key_id
ORDER BY tak.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllTrialAPIKeysParams struct {
	Limit  int32
	Offset int32
}

type ListAllTrialAPIKeysRow struct {
	ID                   uuid.UUID
	KeyHash              string
	KeyPrefix            string
	DeviceFingerprint    string
	CreatedAt            sql.NullTime
	ExpiresAt            time.Time
	LastUsedAt           sql.NullTime
	RevokedAt            sql.NullTime
	TotalSessions        int64
	TotalDurationSeconds string
}

// =====================
// ADMIN TRIAL QUERIES
// =====================
func (q *Queries) ListAllTrialAPIKeys(ctx context.Context, arg ListAllTrialAPIKeysParams) ([]ListAllTrialAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTrialAPIKeys, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTrialAPIKeysRow
	for rows.Next() {
		var i ListAllTrialAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.DeviceFingerprint,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.TotalSessions,
			&i.TotalDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTrialUsageLogs = `-- name: ListAllTrialUsageLogs :many
SELECT
    tu.id, tu.trial_key_id, tu.started_at, tu.ended_at, tu.duration_seconds, tu.status, tu.error_message, tu.deepgram_params, tu.bytes_sent, tu.client_ip,
    tak.key_prefix,
    tak.device_fingerprint
FROM trial_usage tu
JOIN trial_api_keys tak ON tu.trial_key_id = tak.id
ORDER BY tu.started_at DESC
LIMIT $1 OFFSET $2
`

type ListAllTrialUsageLogsParams struct {
	Limit  int32
	Offset int32
}

type ListAllTrialUsageLogsRow struct {
	ID                uuid.UUID
	TrialKeyID        uuid.UUID
	StartedAt         time.Time
	EndedAt           sql.NullTime
	DurationSeconds   sql.NullString
	Status            string
	ErrorMessage      sql.NullString
	DeepgramParams    json.RawMessage
	BytesSent         int64
	ClientIp          sql.NullString
	KeyPrefix         string
	DeviceFingerprint string
}

func (q *Queries) ListAllTrialUsageLogs(ctx context.Context, arg ListAllTrialUsageLogsParams) ([]ListAllTrialUsageLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTrialUsageLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTrialUsageLogsRow
	for rows.Next() {
		var i ListAllTrialUsageLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TrialKeyID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.Status,
			&i.ErrorMessage,
			&i.DeepgramParams,
			&i.BytesSent,
			&i.ClientIp,
			&i.KeyPrefix,
			&i.DeviceFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrialAPIKeys = `-- name: ListTrialAPIKeys :many
SELECT id, key_hash, key_prefix, device_fingerprint, created_at, expires_at, last_used_at, revoked_at FROM trial_api_keys ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListTrialAPIKeysParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTrialAPIKeys(ctx context.Context, arg ListTrialAPIKeysParams) ([]TrialApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listTrialAPIKeys, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrialApiKey
	for rows.Next() {
		var i TrialApiKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.DeviceFingerprint,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrialUsageLogs = `-- name: ListTrialUsageLogs :many
SELECT id, trial_key_id, started_at, ended_at, duration_seconds, status, error_message, deepgram_params, bytes_sent, client_ip FROM trial_usage WHERE trial_key_id = $1 ORDER BY started_at DESC LIMIT $2 OFFSET $3
`

type ListTrialUsageLogsParams struct {
	TrialKeyID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListTrialUsageLogs(ctx context.Context, arg ListTrialUsageLogsParams) ([]TrialUsage, error) {
	rows, err := q.db.QueryContext(ctx, listTrialUsageLogs, arg.TrialKeyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrialUsage
	for rows.Next() {
		var i TrialUsage
		if err := rows.Scan(
			&i.ID,
			&i.TrialKeyID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.Status,
			&i.ErrorMessage,
			&i.DeepgramParams,
			&i.BytesSent,
			&i.ClientIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTrialAPIKey = `-- name: RevokeTrialAPIKey :exec
UPDATE trial_api_keys SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeTrialAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeTrialAPIKey, id)
	return err
}

const updateTrialAPIKeyLastUsed = `-- name: UpdateTrialAPIKeyLastUsed :exec
UPDATE trial_api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateTrialAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateTrialAPIKeyLastUsed, id)
	return err
}

const updateTrialLimits = `-- name: UpdateTrialLimits :one
UPDATE trial_limits
SET max_duration_seconds = $1,
    max_sessions = $2,
    max_session_duration_seconds = $3,
    expiry_days = $4,
    updated_at = NOW()
WHERE id = 1
RETURNING id, max_duration_seconds, max_sessions, max_session_duration_seconds, expiry_days, updated_at
`

type UpdateTrialLimitsParams struct {
	MaxDurationSeconds        int32
	MaxSessions               int32
	MaxSessionDurationSeconds int32
	ExpiryDays                int32
}

func (q *Queries) UpdateTrialLimits(ctx context.Context, arg UpdateTrialLimitsParams) (TrialLimit, error) {
	row := q.db.QueryRowContext(ctx, updateTrialLimits,
		arg.MaxDurationSeconds,
		arg.MaxSessions,
		arg.MaxSessionDurationSeconds,
		arg.ExpiryDays,
	)
	var i TrialLimit
	err := row.Scan(
		&i.ID,
		&i.MaxDurationSeconds,
		&i.MaxSessions,
		&i.MaxSessionDurationSeconds,
		&i.ExpiryDays,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrialUsageComplete = `-- name: UpdateTrialUsageComplete :exec
UPDATE trial_usage
SET ended_at = NOW(),
    duration_seconds = $2,
    status = 'completed',
    bytes_sent = $3
WHERE id = $1
`

type UpdateTrialUsageCompleteParams struct {
	ID              uuid.UUID
	DurationSeconds sql.NullString
	BytesSent       int64
}

func (q *Queries) UpdateTrialUsageComplete(ctx context.Context, arg UpdateTrialUsageCompleteParams) error {
	_, err := q.db.ExecContext(ctx, updateTrialUsageComplete, arg.ID, arg.DurationSeconds, arg.BytesSent)
	return err
}

const updateTrialUsageError = `-- name: UpdateTrialUsageError :exec
UPDATE trial_usage
SET ended_at = NOW(),
    status = 'error',
    error_message = $2,
    bytes_sent = $3
WHERE id = $1
`

type UpdateTrialUsageErrorParams struct {
	ID           uuid.UUID
	ErrorMessage sql.NullString
	BytesSent    int64
}

func (q *Queries) UpdateTrialUsageError(ctx context.Context, arg UpdateTrialUsageErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateTrialUsageError, arg.ID, arg.ErrorMessage, arg.BytesSent)
	return err
}

const updateTrialUsageTimeout = `-- name: UpdateTrialUsageTimeout :exec
UPDATE trial_usage
SET ended_at = NOW(),
    status = 'timeout',
    bytes_sent = $2
WHERE id = $1
`

type UpdateTrialUsageTimeoutParams struct {
	ID        uuid.UUID
	BytesSent int64
}

func (q *Queries) UpdateTrialUsageTimeout(ctx context.Context, arg UpdateTrialUsageTimeoutParams) error {
	_, err := q.db.ExecContext(ctx, updateTrialUsageTimeout, arg.ID, arg.BytesSent)
	return err
}
